# Generated by Django 6.0.6 on 2026-07-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedpost",
            name="file",
            field=models.FileField(blank=True, upload_to="posts/"),
        ),
    ]
